[package]
name = "waypoint_based_destructible_terrain"
version = "0.16.0"
authors = ["Armin Sch√§fer"]
readme = "README.md"
edition = "2021"
keywords = ["Indie"]

[dependencies]
bevy = "0.16.0"
rand = "0.9.1"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
